publish_to: none

name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.1.0
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
    sdk: ">=3.0.0 <4.0.0"
    flutter: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_test:
        sdk: flutter
    flutter_driver:
        sdk: flutter
    meta:
    gherkin: ^3.0.1
    # gherkin:
    #     path: ../dart_gherkin

dev_dependencies:
    test:
    pedantic:
dependency_overrides:
    gherkin:
        git:
            url: https://github.com/therealmodbom/dart_gherkin.git
